var helloWorld="Omais Rao";
var aGe="18 year old";
var corUse="Certified Moblie App Devolper";
var pIzza="pizza \n pizz \n piz \n pi\n p";
var eMail="My emai is ranaomais92@gmail.com";
var boOk="I am trying to Learn Form the Book A Samter Way To Learn JS";
alert(helloWorld);
alert(aGe);
alert(corUse);
alert(pIzza);
alert(eMail);
alert(boOk);